package de.hska.vslab.categories;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
public class CategoryController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CategoryRepository categoryRepository;

    @PostMapping(path="/categories") // Map ONLY POST Requests
    public @ResponseBody String addNewCategory(@RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Category category = new Category();
        category.setName(name);
        categoryRepository.save(category);
        return "Saved";
    }

    @GetMapping(path="/categories")
    public @ResponseBody Iterable<Category> getAllCategories() {
        // This returns a JSON or XML with the users
        return categoryRepository.findAll();
    }

    @GetMapping(path="/categories/{id}")
    public @ResponseBody Category getCategoryById(@PathVariable Integer id) {
        // This returns a JSON or XML with the users
        var result = categoryRepository.findById(id);
        return result.orElse(null);
    }
}